export const actions = {
  GET_SESSIONS: "GET_SESSIONS",
  GET_SESSION: "GET_SESSION",
  ADD_SESSION: "ADD_SESSION",
  DELETE_SESSION: "DELETE_SESSION",
  UPDATE_STATUS: "UPDATE_STATUS",
  ADD_PLAYER: "ADD_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  UPDATE_FINAL_IMAGE: "UPDATE_FINAL_IMAGE"
};
