export const REQUEST_STATE = {
    IDLE: 'IDLE',
    PENDING: 'PENDING',
    FULFILLED: 'FULFILLED',
    REJECTED: 'REJECTED'
};

export const GET_SESSIONS = "GET_SESSIONS";
export const ADD_SESSION = "ADD_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";
export const UPDATE_STATUS = "UPDATE_STATUS"
export const ADD_PLAYER = "ADD_PLAYER";
export const FINAL_IMAGE = "FINAL_IMAGE";